"""add user_reports table

Revision ID: e0601c21585c
Revises: 210c14dbf05f
Create Date: 2026-07-12 01:44:39.043149
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e0601c21585c'
down_revision: Union[str, None] = '210c14dbf05f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create enum type before altering column (PostgreSQL needs it)
    bind = op.get_bind()
    if bind.engine.name == "postgresql":
        bind.execute(sa.text("""
            DO $$ BEGIN
                CREATE TYPE studymode AS ENUM ('offline', 'online', 'focus', 'exam', 'custom', 'pomodoro');
            EXCEPTION WHEN duplicate_object THEN null;
            END $$;
        """))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('report_type', sa.String(length=10), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('highlights', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_reports_report_type'), 'user_reports', ['report_type'], unique=False)
    op.create_index(op.f('ix_user_reports_user_id'), 'user_reports', ['user_id'], unique=False)
    op.create_foreign_key(None, 'quiz_sessions', 'topics', ['topic_id'], ['id'])
    op.alter_column('sessions', 'mode',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('offline', 'online', 'focus', 'exam', 'custom', 'pomodoro', name='studymode'),
               existing_nullable=False)
    op.create_foreign_key(None, 'sessions', 'topics', ['topic_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.alter_column('sessions', 'mode',
               existing_type=sa.Enum('offline', 'online', 'focus', 'exam', 'custom', 'pomodoro', name='studymode'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
    op.drop_constraint(None, 'quiz_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_user_reports_user_id'), table_name='user_reports')
    op.drop_index(op.f('ix_user_reports_report_type'), table_name='user_reports')
    op.drop_table('user_reports')
    # ### end Alembic commands ###
